version: 0.2.0.{build}

image:
  - Visual Studio 2017
  - Ubuntu1604

platform:
  - x64

environment:
  QT_DIR_WIN_32: C:\Qt\5.12.6\msvc2017
  QT_DIR_WIN_64: C:\Qt\5.12.6\msvc2017_64

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017

    init:
      - ver
      - cmake --version

    cache:
      - build-msvc15_x64 -> appveyor-build.ps1
      - build-msvc15_x86 -> appveyor-build.ps1
      - build-cmd-msvc15_x64 -> appveyor-build.ps1
      - build-cmd-msvc15_x86 -> appveyor-build.ps1

    before_build:
      - git submodule update --init

    build_script:
      - ps: $env:Path = "C:\Python38\;" + $env:Path
      - ps: ./appveyor-build.ps1

    artifacts:
      - path: bin-msvc15_x64
        type: zip
        name: SpaceDisplay-msvc15-x64

      - path: bin-msvc15_x86
        type: zip
        name: SpaceDisplay-msvc15-x86

      - path: bin-cmd-msvc15_x64
        type: zip
        name: SpaceDisplay-cmd-msvc15-x64

      - path: bin-cmd-msvc15_x86
        type: zip
        name: SpaceDisplay-cmd-msvc15-x86
  -
    matrix:
      only:
        - image: Ubuntu1604

    init:
      - cmake --version
      - gcc -v

    install:
      - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
      - sudo apt-get update -qq
      - sudo apt-get -y install qtbase5-dev libqt5svg5-dev qt5-default
      - mkdir tools && cd tools
      # fetch linuxdeploy and qt plugin
      - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
      - wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
      - chmod a+x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage
      - cd ..

    before_build:
      - git submodule update --init

    build_script:
      - echo Ubuntu build script
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
      - make
      - make install DESTDIR=AppDir
      - mv AppDir/usr/bin/spacedisplay_gui AppDir/usr/bin/spacedisplay
      - ../tools/linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage
      - mv Space_Display*.AppImage SpaceDisplay-x86_64.AppImage
      - cd ..

    artifacts:
      - path: build/SpaceDisplay-x86_64.AppImage
        type: File
        name: SpaceDisplay-x86_64.AppImage


deploy:
  release: SpaceDisplay v$(appveyor_build_version)
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: 6xHQBZVK+RtxmddurGPIg7Kx5vecSN1vVxwbv35EQmsIey4DXDXYhwAW/yLXbNLJ
  artifact: SpaceDisplay-msvc15-x64, SpaceDisplay-msvc15-x86, SpaceDisplay-cmd-msvc15-x64, SpaceDisplay-cmd-msvc15-x86, SpaceDisplay-x86_64.AppImage
  draft: true
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
