version: 0.5.0.{build}

image:
  - Visual Studio 2017
  - Ubuntu1604

platform:
  - x64

environment:
  QT_DIR_WIN_32_XP: C:\Qt\5.6.3\msvc2015
  QT_DIR_WIN_32: C:\Qt\5.12.6\msvc2017
  QT_DIR_WIN_64: C:\Qt\5.12.6\msvc2017_64

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017

    init:
      - ver
      - cmake --version

    cache:
      - build-msvc15_x64 -> appveyor-build.ps1
      - build-msvc15_x86 -> appveyor-build.ps1

    before_build:
      - git submodule update --init

    build_script:
      - ps: $env:Path = "C:\Python38\;" + $env:Path
      - ps: ./ci/appveyor-build.ps1

    artifacts:
      - path: bin-msvc15_x64
        type: zip
        name: SpaceDisplay-msvc15-x64

      - path: bin-msvc15_x86
        type: zip
        name: SpaceDisplay-msvc15-x86

      - path: bin-msvc15_x86_xp
        type: zip
        name: SpaceDisplay-msvc15-x86-xp
  -
    matrix:
      only:
        - image: Ubuntu1604

    init:
      - cmake --version
      - gcc -v

    cache:
      - build -> ci/appveyor-build.sh
      - tools -> ci/appveyor-install.sh

    install:
      - ./ci/appveyor-install.sh

    before_build:
      - git submodule update --init

    build_script:
      - ./ci/appveyor-build.sh

    artifacts:
      - path: bin/SpaceDisplay-x86_64.AppImage
        type: File
        name: SpaceDisplay-x86_64.AppImage


deploy:
  release: SpaceDisplay v$(appveyor_build_version)
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: 6xHQBZVK+RtxmddurGPIg7Kx5vecSN1vVxwbv35EQmsIey4DXDXYhwAW/yLXbNLJ
  artifact: SpaceDisplay-msvc15-x64, SpaceDisplay-msvc15-x86, SpaceDisplay-msvc15-x86-xp, SpaceDisplay-x86_64.AppImage
  draft: true
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
