name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-win:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qt/'

      - name: Create Build Environment
        run: cmake -E make_directory '${{github.workspace}}'/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake .. -DQT_WIN_PATH='${{env.Qt5_Dir}}' -DWIN32_CONSOLE="Off" -G "Visual Studio 16 2019" -A x64

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      # upload binaries
      - name: Upload Example binary
        uses: actions/upload-artifact@v2
        with:
          name: upload binary
          path: ${{github.workspace}}/build/app-gui
