name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qt/'
          modules: 'qtsvg'

      - name: Create Build Environment
        run: cmake -E make_directory build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake -DQT_WIN_PATH='${{env.Qt5_Dir}}' -DWIN32_CONSOLE="Off" -G "Visual Studio 16 2019" -A x64 ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Copy necessary dlls
        working-directory: ${{github.workspace}}/build
        run: |
          cp ${{env.Qt5_Dir}}/bin/Qt5Core.dll Qt5Core.dll
          cp ${{env.Qt5_Dir}}/bin/Qt5Gui.dll Qt5Gui.dll
          cp ${{env.Qt5_Dir}}/bin/Qt5Widgets.dll Qt5Widgets.dll
          cp ${{env.Qt5_Dir}}/bin/Qt5Svg.dll Qt5Svg.dll
          mkdir platforms
          cp ${{env.Qt5_Dir}}/plugins/platforms/qwindows.dll platforms/qwindows.dll

      # upload binaries
      - name: Upload windows binary
        uses: actions/upload-artifact@v2
        with:
          name: spacedisplay-msvc19-x64
          path: ${{github.workspace}}/build/app-gui/Release
