name: Release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/tags/latest'
    runs-on: ubuntu-latest
    steps:
      - name: version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
        id: version

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          name: SpaceDisplay ${{ steps.version.outputs.version }}
          draft: false
          prerelease: true
